In [1]:
import pandas as pd 
import numpy as np

In [5]:
df = pd.read_csv('data/bank_churn.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/bank_churn.csv'

In [9]:
df = pd.read_csv('../data/bank_churn.csv')

In [10]:

df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
df.shape

(10000, 13)

In [13]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'Num Of Products', 'Has Credit Card',
       'Is Active Member', 'Estimated Salary', 'Churn'],
      dtype='object')

In [14]:
df.dtypes

CustomerId            int64
Surname              object
CreditScore           int64
Geography            object
Gender               object
Age                   int64
Tenure                int64
Balance             float64
Num Of Products       int64
Has Credit Card       int64
Is Active Member      int64
Estimated Salary    float64
Churn                 int64
dtype: object

In [15]:
df.isna().sum()

CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    0
Churn               0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [17]:
df.columns.tolist()

['CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'Num Of Products',
 'Has Credit Card',
 'Is Active Member',
 'Estimated Salary',
 'Churn']

In [19]:
df["Churn"].value_counts()
df["Churn"].value_counts(normalize=True)

Churn
0    0.7963
1    0.2037
Name: proportion, dtype: float64

In [21]:
df.isnull().sum().sort_values(ascending=False)

CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    0
Churn               0
dtype: int64

In [22]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [44]:
for col in df.select_dtypes(include='object').columns:
    print(col,df[col].nunique())
    print(df[col].unique())
    print(f"the highest value is: {df[col].value_counts().idxmax()} with {(df[col].value_counts().max())/(len(df))*100:.2f}%")

Surname 2932
['Hargrave' 'Hill' 'Onio' ... 'Kashiwagi' 'Aldridge' 'Burbidge']
the highest value is: Smith with 0.32%
Geography 3
['France' 'Spain' 'Germany']
the highest value is: France with 50.14%
Gender 2
['Female' 'Male']
the highest value is: Male with 54.57%

In [29]:
for col in df.select_dtypes(include='object').columns:
    
    print(df[col].value_counts())
    print("~" * 39)

Surname
Smith       32
Scott       29
Martin      29
Walker      28
Brown       26
            ..
Izmailov     1
Bold         1
Bonham       1
Poninski     1
Burbidge     1
Name: count, Length: 2932, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Gender
Male      5457
Female    4543
Name: count, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [45]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.groupby("Churn")["CreditScore"].mean()

Churn
0    651.853196
1    645.351497
Name: CreditScore, dtype: float64

In [47]:
df.groupby('Churn')["CreditScore"].describe()

        count        mean         std    min    25%    50%    75%    max
Churn
0      7963.0  651.853196   95.653837  405.0  585.0  653.0  718.0  850.0
1      2037.0  645.351497  100.321503  350.0  578.0  646.0  716.0  850.0

In [ ]:
df[df["Churn"] == 1]["CreditScore"].mean()

651.8531960316463

In [49]:
df[df["Churn"] == 0]["CreditScore"].mean()

651.8531960316463

In [51]:
df.groupby("Churn")["Age"].mean()

Churn
0    37.408389
1    44.837997
Name: Age, dtype: float64

In [53]:
df.groupby("Churn")["Balance"].mean()

Churn
0    72745.296779
1    91108.539337
Name: Balance, dtype: float64

In [54]:
df.groupby("Geography")["Churn"].mean()

Geography
France     0.161548
Germany    0.324432
Spain      0.166734
Name: Churn, dtype: float64

In [55]:
df.head(
    
)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [56]:
df.select_dtypes(include=[int,float]).columns.tolist()

['CustomerId',
 'CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'Num Of Products',
 'Has Credit Card',
 'Is Active Member',
 'Estimated Salary',
 'Churn']

In [57]:
"df.select_dtypes(include=[object]).columns.tolist()"

'df.select_dtypes(include=[object]).columns.tolist()'

In [58]:
df.select_dtypes(include=[object]).columns.tolist()

['Surname', 'Geography', 'Gender']